// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfnnCUOkQjCvrfk74D0Wtmk7EfFYU6Sps',
    appId: '1:127506835883:web:753322f5dbad668f038aee',
    messagingSenderId: '127506835883',
    projectId: 'auth-2-3cf8e',
    authDomain: 'auth-2-3cf8e.firebaseapp.com',
    storageBucket: 'auth-2-3cf8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS98d0MPjTraSsMe0SVXeLGMatsiwFFts',
    appId: '1:127506835883:android:f15b648531833110038aee',
    messagingSenderId: '127506835883',
    projectId: 'auth-2-3cf8e',
    storageBucket: 'auth-2-3cf8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiF_iGdoMWTG1FYQyRAi8yhiNdII96sXQ',
    appId: '1:127506835883:ios:7362e5d46cccad55038aee',
    messagingSenderId: '127506835883',
    projectId: 'auth-2-3cf8e',
    storageBucket: 'auth-2-3cf8e.appspot.com',
    iosBundleId: 'com.example.firebaseAuth2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiF_iGdoMWTG1FYQyRAi8yhiNdII96sXQ',
    appId: '1:127506835883:ios:3f6ac0647817de72038aee',
    messagingSenderId: '127506835883',
    projectId: 'auth-2-3cf8e',
    storageBucket: 'auth-2-3cf8e.appspot.com',
    iosBundleId: 'com.example.firebaseAuth2.RunnerTests',
  );
}
